name: Auto Update

# Controls when the workflow will run
on:
  workflow_dispatch: # Allows workflow to be manually triggered from Actions page
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight

jobs:
  pipenv-upgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv
      - name: Update dependencies
        run: pipenv lock
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Auto Pipenv Update"
          body: "This PR was created automatically by the Auto Update workflow."
          signoff: true
          commit-message: "Update dependencies via `pipenv lock`."
          branch: "create-pull-request/auto-update/pipenv"
          branch-suffix: "timestamp"
          labels: "auto-update,dependencies,python"
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
